### ISSUE TITLE
Why are there front end and backend job, if can i need to do the fullstack ?

### ISSUE THREAD

**Issue by nicholasess** [entria/jobs#15]

**Comment by sibelius** [comment]
Everybody at :entria:  is a FullStack Engineer/Developer

We provide frontend and backend challenges as a path to learning both and finish the FullStack challenge.

We also provide a list of skills that would help when working in Entria projects - https://github.com/entria/jobs/blob/master/skills.md

Maybe we should make this more explicit on readme

Usually developers are afraid of fullstack as it looks like too much knowledge
