### ISSUE TITLE
use gatsby to jobs.entria.com.br

### ISSUE THREAD

**Issue by sibelius** [entria/jobs#20]
Based on this template

https://github.com/emcasa/jobs

**Comment by nicholasess** [comment]
@sibelius in settings you can set ```gh-pages``` with branch master and path ```docs```. And set build path called ```docs``` in the gatsby.

**Comment by nicholasess** [comment]
@sibelius Is there image from team for background image?

**Comment by sibelius** [comment]
docusaurus is easier and better for this
