### ISSUE TITLE
Sobre fetch API

### ISSUE THREAD

**Issue by maugravena** [entria/jobs#4]
fetch é uma web api, utilizar axios não seria mais apropriado?

**Comment by sibelius** [comment]
we recommend use of this package https://github.com/matthew-andrews/isomorphic-fetch

so we can use the same code on backend and frontend

axios is just an abstration on top of fetch or XMLHttpRequest

you can do the same in a more functional way like this https://gist.github.com/sibelius/13db50b2739c8ffcf03fc5c1e8310de4
